name: Create new Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    container:
      image: node:16.17
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build plugin
        run: |
          yarn install
          yarn build && yarn build-dev
      - name: Prepare SBOM generation
        run: mkdir boomerang-opentelemetry-sboms
      - name: Generate XML SBOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          output: ./boomerang-opentelemetry-sboms/boomerang-opentelemetry-sbom.xml
      - name: Generate JSON SBOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          output: ./boomerang-opentelemetry-sboms/boomerang-opentelemetry-sbom.json
          json: true
      - name: Package SBOMs
        run: |
          apt-get update && apt-get install zip
          zip -r dist/boomerang-opentelemetry-sboms.zip boomerang-opentelemetry-sboms
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
